# Generated by Django 2.2.5 on 2019-12-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
