# Generated by Django 2.2.5 on 2019-10-12 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_auto_20191012_2348'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
