# Generated by Django 2.2.5 on 2019-10-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_meeting_present_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='present_code',
            field=models.TextField(max_length=10),
        ),
    ]
