# Generated by Django 2.2.5 on 2019-10-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_auto_20191009_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='present_code',
            field=models.CharField(max_length=16),
        ),
    ]
