# Generated by Django 2.2.5 on 2019-10-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_auto_20191009_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='present_code',
        ),
        migrations.AddField(
            model_name='meeting',
            name='code',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
