# Generated by Django 2.2.5 on 2019-10-09 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0008_attendance_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='meeting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meetings.Meeting'),
            preserve_default=False,
        ),
    ]
