# Generated by Django 2.2.5 on 2019-10-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0009_attendance_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='code',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
