# Generated by Django 2.2.8 on 2019-12-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_url',
            field=models.CharField(default='https://akai.org.pl/img/logo.svg', max_length=255),
        ),
    ]
